/**
 * data.ts — client-side loaders for the baked rarity data (generated by scripts/build-data.ts).
 *
 *   summary.json     -> { methods, total, defaultMethod, ranks: { <method>: number[] } }
 *                       each ranks[method] is length `total`, indexed by (serial - 1). Loaded once,
 *                       kept in memory; powers instant search / sort / the grid under any method.
 *   detail/<b>.json  -> { "<serial>": { ranks, scores, traits } }, buckets of 100 serials.
 *                       Lazy-fetched only when a detail / compare card needs it; cached per bucket.
 *
 * Everything is static under /public/data, so these are plain cached fetches — no API, no network
 * beyond the first load of each file.
 */
import { config } from '@/config'
import type { RarityMethod } from '@/config'

export const TOTAL = config.total
const BUCKET = 100

export type MethodRanks = Record<RarityMethod, number[]>
export type Summary = {
  methods: RarityMethod[]
  total: number
  defaultMethod: RarityMethod
  ranks: MethodRanks
}
export type Trait = { trait_type: string; value: string; count: number; pct: number }
export type Detail = {
  ranks: Record<RarityMethod, number>
  scores: Record<RarityMethod, number>
  traits: Trait[]
}

let summaryPromise: Promise<Summary> | null = null
const bucketCache = new Map<number, Promise<Record<string, Detail>>>()

/** The full rank data (all methods), cached after the first call. */
export function loadSummary(): Promise<Summary> {
  if (!summaryPromise) {
    summaryPromise = fetch('/data/summary.json')
      .then((r) => {
        if (!r.ok) throw new Error(`summary.json ${r.status}`)
        return r.json()
      })
      .catch((err) => {
        summaryPromise = null // allow retry on failure
        throw err
      })
  }
  return summaryPromise
}

/** Full detail (ranks, scores, traits) for one serial. Fetches + caches its 100-serial bucket. */
export async function loadDetail(serial: number): Promise<Detail | null> {
  if (!Number.isInteger(serial) || serial < 1 || serial > TOTAL) return null
  const b = Math.floor((serial - 1) / BUCKET)
  let p = bucketCache.get(b)
  if (!p) {
    p = fetch(`/data/detail/${b}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`detail/${b}.json ${r.status}`)
        return r.json()
      })
      .catch((err) => {
        bucketCache.delete(b) // allow retry
        throw err
      })
    bucketCache.set(b, p)
  }
  const bucket = await p
  return bucket[String(serial)] ?? null
}
